export enum FieldCode {
  LOGO_TEXT = 'LOGO_TEXT',
  RUC_MATCH = 'RUC_MATCH',
  RUC_INPUT = 'RUC_INPUT',
  RUC_STATUS = 'RUC_STATUS',
  RUC_CONDITION = 'RUC_CONDITION',
  DOCUMENT_TYPE = 'DOCUMENT_TYPE',
  DOCUMENT_ITEMS = 'DOCUMENT_ITEMS',
  CONSUMPTION_TEXT = 'POR_CONSUMO'
}

export enum RucInput {
  LENGTH = 11
}

export enum RucStatus {
  ACTIVO = 'ACTIVO',
  SUSPENSION_TEMPORAL = 'SUSPENSION _TEMPORAL',
  BAJA_PROVISIONAL = 'BAJA_PROVISIONAL',
  BAJA_DEFINITIVA = 'BAJA_DEFINITIVA',
  BAJA_PROVISIONAL_DE_OFICIO = 'BAJA_PROVISIONAL_DE_OFICIO',
  BAJA_DEFINITIVA_DE_OFICIO = 'BAJA_DEFINITIVA_DE_OFICIO',
}

export enum RucCondition {
  HABIDO = 'HABIDO',
  NO_HABIDO = 'NO HABIDO',
  NO_HALLADO = 'NO HALLADO',
}

export enum DocumentType {
  ANTICIPO_CLIENTE = 'AC',
  ANTICIPOS_DE_PROVEEDORES = 'AP',
  AVANCE_EN_CUENTA = 'AV',
  B_VIAJE_INTERPR_S_IGV = 'BVIAJE S/I',
  B_VIAJE_NACIONAL = 'B.VIAJE',
  BOLETA_NO_EMITIDA = 'BN',
  BOLETAS_DE_VENTAS = 'BV',
  BOLETO_DE_AVION = 'BA',
  BOLETO_TRANSPORTE_PUBLICO = 'BT',
  BV_POR_COMPRAS = 'BC',
  CARTA_DE_PORTE_AEREO = 'CPA',
  COBRANZA_DUDOSA = 'COB.DUDOSA',
  COMPROBANTE_BANCO = 'CB',
  COMPROBANTE_BANCO_LEASING = 'CL',
  COMPROBANTE_DE_PERCEPCION = 'CPR',
  CREDITO_DIRECTO = 'CD',
  DECLARACION_UNICA_DE_ADUANA = 'DUA',
  DETRACCION = 'DT',
  DETRACCION_VENTA = 'VT',
  DOC_VAR_PROVEEDORES = 'DOC.VAR',
  FACTURA_DE_COMPRAS = 'FC',
  FACTURA_DE_COMPRAS_POR_DSCTO = 'FACOM',
  FACTURA_DE_EPS = 'FE',
  FACTURA_DE_EXPORTACION_VENTA = 'FX',
  FACTURA_DE_HOTELES_Y_REST = 'FH',
  FACTURA_DE_VENTA = 'FV',
  FACTURA_EXONERADA_VENT_SIN_IGV = 'FEXO',
  FACTURA_NO_DOMICILIADO = 'FN',
  FACTURA_NO_EMITIDA = 'F1',
  FACTURA_POR_RECIBIR = 'FR',
  FACTURA_SIN_IGV = 'FSIGV',
  FACTURA_SIN_IGV_VENTA = 'FSIV',
  FORMUL_DECLAR_O_BOLETA_TRIBUT = 'FT',
  INVOICE = 'NR',
  LEASING = 'CB',
  LETRAS_POR_COBRAR = 'LC',
  LETRAS_POR_PAGAR = 'LP',
  NOTA_CREDITO_COMPRA_CON_IGV = 'NC',
  NOTA_CREDITO_COMPRA_SIN_IGV = 'NC',
  NOTA_CREDITO_VENTA_CON_IGV = 'NC',
  NOTA_CREDITO_VENTA_SIN_IGV = 'NC',
  NOTA_CREDITO_VENTAS_EXPORTA = 'NC',
  NOTA_DE_CONTABILIDAD = 'NCONT',
  NOTA_DE_CREDITO_HOTELES_Y_REST = 'NC',
  NOTA_DE_DEBITO_POR_COMPRAS = 'ND',
  NOTA_DE_DEBITO_VENTAS = 'ND',
  NOTA_DEBITO_POR_COMPRAS_S_IGV = 'ND',
  OTROS_FACT_DE_EXPORTACION = 'FX',
  PAGARE = 'PA',
  PRESTAMOS = 'PT',
  RECIBO_BANCO_IGV_NO_DOM = 'RN',
  RECIBO_BANCO_NACION = 'RBN',
  RECIBO_PODER_JUDICIAL = 'RJUD',
  RECIBO_POR_ARRENDAMIENTO = 'RA',
  RECIBO_POR_HONORARIOS = 'RH',
  RECIBO_REGISTRO_PUBLICO = 'RPUB',
  RECIBO_SERVICIOS_PUBLICOS = 'RS',
  TARIFA_UNIF_DE_USO_DE_AEROPUE = 'TUA',
  TICKET_MAQUINA_REGISTRADORA = 'TK'
}

export enum DocumentSection {
  ENCABEZADO = 'ENCABEZADO'
}