COD_RUBRO_MOVILIDAD=GGENE
COD_TIPO_GASTO_MOVILIDAD=0409
COD_RUBRO_GENERAL=GGENE
COD_TIPO_GASTO_GENERAL=0102
COD_DOCUMENTO_GENERAL=FC
LST_DIVISION_GASTO='9430206','9430207','9430305','9430314','9430303', '9430304'

# === Reglas de Planilla de Movilidad ===
# Importe maximo permitido por dia (en Soles) para gastos de movilidad
PLANILLA_MOVILIDAD_IMPORTE_MAX_DIA=45.20